---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: motioneye-image
    newName: docker.io/ccrisan/motioneye
    newTag: master-amd64
patches:
  - target:
      kind: Route
      name: motion-config
    patch: |-
      - op: replace
        path: /spec/host
        value: motion-config.apps.dell-3200.cool.lab
  - target:
      kind: Route
      name: motion-stream
    patch: |-
      - op: replace
        path: /spec/host
        value: motion-stream.apps.dell-3200.cool.lab
  - target:
      kind: Route
      name: motion-front
    patch: |-
      - op: replace
        path: /spec/host
        value: motioneye.apps.dell-3200.cool.lab
