---
apiVersion: v1
kind: Namespace
metadata:
  name: motion-eye

---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: motion-eye
  namespace: motion-eye
  labels:
    app: motion-eye
spec:
  type: Git
  pathname: https://github.com/ikke-t/motioneye-microshift.git

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: motion-eye
  namespace: motion-eye
  labels:
    app: motion-eye
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - motion-eye-argocd

---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: motion-eye
  namespace: motion-eye
  labels:
    app: motion-eye
  annotations:
    apps.open-cluster-management.io/git-path: argocd
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: motion-eye/motion-eye
  placement:
    placementRef:
      kind: PlacementRule
      name: motion-eye
  overrides:
    # - clusterName: "*"
    - clusterName: "fi-sno-01"
      clusterOverrides:
        - path: "metadata.namespace"
          value: openshift-gitops

---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: motion-eye
  namespace: motion-eye
  labels:
    app: motion-eye
spec:
  selector:
    matchLabels:
      app: motion-eye
