---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - motioneye-clusterrolebinding.yaml
  - motioneye-clusterrole.yaml
  - motioneye-deployment.yaml
  - motioneye-namespace.yaml
  - motioneye-route.yaml
  - motioneye-sa.yaml
  - motioneye-scc.yaml
  - motioneye-service.yaml
  - motioneye-storage.yaml
