---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: motion
  namespace: motion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: motion
subjects:
- kind: ServiceAccount
  name: motion
  namespace: motion
