apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: motion
  namespace: motion
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - motion
  verbs:
  - use
